export enum ConfigurationScope {
  PLATFORM = 'PLATFORM',
  ORGANIZATION = 'ORGANIZATION',
  LEGAL_ENTITY = 'LEGAL_ENTITY',
  BUSINESS_UNIT = 'BUSINESS_UNIT',
  DIVISION = 'DIVISION',
  REGION = 'REGION',
  BRANCH = 'BRANCH',
  DEPARTMENT = 'DEPARTMENT',
  TEAM = 'TEAM',
  USER = 'USER',
}
