export enum AssignmentType {
  USER = 'USER',
  ROLE = 'ROLE',
  TEAM = 'TEAM',
  DEPARTMENT = 'DEPARTMENT',
  ORGANIZATION_NODE = 'ORGANIZATION_NODE',
  EXPRESSION = 'EXPRESSION',
  AI_RECOMMENDATION = 'AI_RECOMMENDATION',
}
