export enum WorkflowStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
  RUNNING = 'RUNNING',
  WAITING = 'WAITING',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  ESCALATED = 'ESCALATED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}
