export enum RuleType {
  VALIDATION = 'VALIDATION',
  DECISION = 'DECISION',
  ROUTING = 'ROUTING',
  CALCULATION = 'CALCULATION',
  ELIGIBILITY = 'ELIGIBILITY',
  SECURITY = 'SECURITY',
  VISIBILITY = 'VISIBILITY',
  TRANSFORMATION = 'TRANSFORMATION',
}
