export enum AuditCategory {
  SYSTEM = 'SYSTEM',
  SECURITY = 'SECURITY',
  USER = 'USER',
  DATA = 'DATA',
  INTEGRATION = 'INTEGRATION',
  WORKFLOW = 'WORKFLOW',
  CONFIGURATION = 'CONFIGURATION',
}
